export const GALLERY_ITEMS = [
  { id: 101, src: "/gallery/PIERCING_V2.png", style: "Piercing", artist: "Aishwarya", year: 2026 },
  { id: 102, src: "/gallery/PIERCING_V2_2.png", style: "Piercing", artist: "Thiyagu", year: 2026 },
  { id: 103, src: "/gallery/PIERCING_3.png", style: "Piercing", artist: "Aishwarya", year: 2026 },
  { id: 104, src: "/gallery/PIERCING_4.png", style: "Piercing", artist: "Thiyagu", year: 2026 },
  { id: 1, src: "/gallery/Appa_portrait_tattoo_______appa_trending_tattoo_dad.webp", style: "Portrait", artist: "Thiyagu", year: 2024 },
  { id: 2, src: "/gallery/Buddha_with_lakhey_tattoo_________180_tattoo_studio__BUDDHA____emphasize_inner_peace__mindfulnes__1_.webp", style: "Realism", artist: "Thiyagu", year: 2023 },
  { id: 3, src: "/gallery/Coverup_tattoo________coveruptattoos__tattoo_chennai__malaysia.webp", style: "Custom", artist: "Aishwarya", year: 2023 },
  { id: 4, src: "/gallery/Deadpool_Color_tattoo__________deadpool__maravel__hollywood__tattoo.webp", style: "Colour", artist: "Thiyagu", year: 2024 },
  { id: 5, src: "/gallery/Dragon____tattoo_______dragon_tattoo_uniquetattoos__180tattoostudio.webp", style: "Custom", artist: "Aishwarya", year: 2024 },
  { id: 6, src: "/gallery/IMG_0015.webp", style: "Blackwork", artist: "Thiyagu", year: 2023 },
  { id: 7, src: "/gallery/IMG_0156.webp", style: "Fine Line", artist: "Aishwarya", year: 2024 },
  { id: 8, src: "/gallery/IMG_0488.webp", style: "Realism", artist: "Thiyagu", year: 2023 },
  { id: 9, src: "/gallery/IMG_1832.webp", style: "Blackwork", artist: "Aishwarya", year: 2023 },
  { id: 10, src: "/gallery/Lord_shivan_tattoo____________lordshivan_shivatattoo__devotional__lordtattoo_trendingpost__.webp", style: "Portrait", artist: "Thiyagu", year: 2024 },
  { id: 11, src: "/gallery/Wife_portrait_tattoo________portraittattoo__tattoo_trending_love_.webp", style: "Portrait", artist: "Thiyagu", year: 2024 },
  { id: 12, src: "/gallery/Small_Murugan_vel_tattoo__________for_enquiry_9003157338___murugan_veltattoo_murugan_tamilkadavu.webp", style: "Fine Line", artist: "Aishwarya", year: 2024 },
  { id: 13, src: "/gallery/IMG_0649.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 14, src: "/gallery/IMG_2178.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 15, src: "/gallery/IMG_2361.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 16, src: "/gallery/IMG_2383.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 17, src: "/gallery/IMG_2865.webp", style: "Fine Line", artist: "Aishwarya", year: 2026 },
  { id: 18, src: "/gallery/IMG_3724.webp", style: "Portrait", artist: "Thiyagu", year: 2026 },
  { id: 19, src: "/gallery/IMG_3891.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 20, src: "/gallery/IMG_4032.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 21, src: "/gallery/IMG_4135.webp", style: "Custom", artist: "Aishwarya", year: 2026 },
  { id: 22, src: "/gallery/IMG_4204.webp", style: "Portrait", artist: "Thiyagu", year: 2026 },
  { id: 23, src: "/gallery/IMG_5138.webp", style: "Fine Line", artist: "Aishwarya", year: 2026 },
  { id: 24, src: "/gallery/IMG_5555.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 25, src: "/gallery/IMG_6750.webp", style: "Custom", artist: "Aishwarya", year: 2026 },
  { id: 26, src: "/gallery/IMG_6866.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 27, src: "/gallery/IMG_7476.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 28, src: "/gallery/IMG_8884.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 29, src: "/gallery/IMG_9049.webp", style: "Portrait", artist: "Thiyagu", year: 2026 },
  { id: 30, src: "/gallery/IMG_9660.webp", style: "Portrait", artist: "Thiyagu", year: 2026 },
  { id: 31, src: "/gallery/IMG_9726.webp", style: "Realism", artist: "Thiyagu", year: 2026 },
  { id: 32, src: "/gallery/Small_Murugan_vel_tattoo__________for_enquiry_9003157338___murugan_veltattoo_murugan_tamilkadavu.webp", style: "Fine Line", artist: "Aishwarya", year: 2026 },
  { id: 33, src: "/gallery/tattoo___4.webp", style: "Colour", artist: "Thiyagu", year: 2026 },
  { id: 34, src: "/gallery/Wife_portrait_tattoo________portraittattoo__tattoo_trending_love_.webp", style: "Portrait", artist: "Thiyagu", year: 2026 },
  { id: 35, src: "/gallery/Your_paragraph_text___1.webp", style: "Fine Line", artist: "Aishwarya", year: 2026 },
];

export const TEAM_MEMBERS = [
  {
    id: "aishwarya",
    name: "AISHWARYA",
    role: "Shop Owner & Lead Artist",
    title: "Shop Owner · Professional Artist",
    statement: "As the owner of 180, my focus is on maintaining the highest standards of hygiene and artistic integrity in Chennai. I work side-by-side with Thiyagu to ensure that every client who walks through our doors leaves with a masterpiece. My work is defined by precision, whether it's fine line work or complex blackwork. I believe the studio should be a sanctuary for art.",
    specialties: ["FINE LINE", "BLACKWORK", "REALISM", "PORTRAIT", "CUSTOM"],
    calLink: "180-tattoo-studio/tattoo-with-aishwariya",
    portrait: "/team/Aishwarya___Shop_Owner__.webp"
  },
  {
    id: "thiyagu",
    name: "THIYAGARAJAN",
    role: "Founder & Lead Artist",
    title: "Founder · Tattoo Master",
    statement: "I started 180 in 2019 with Aishwarya. We decided from day one that we were going to set the standard for Chennai. Six years later, every piece that leaves this studio has to pass one test: will this client still love it in twenty years? I specialize in realism and custom portraits. For me, the session is about transferring your vision onto skin with absolute precision.",
    specialties: ["PORTRAIT", "REALISM", "CUSTOM", "BLACKWORK", "COLOUR"],
    calLink: "180-tattoo-studio/tattoo-with-thiyagarajan",
    portrait: "/team/Thiyagarajan___Artist__.webp"
  }
];
